### ISSUE TITLE
Installation in Magento 2.4.4 results in error

### ISSUE THREAD

**Issue by jolovies** [webcodebg/glami#2]
Hello,

We are trying to install the extension in our Magento 2.4.4 environment and we are receiving the error on the attached image. Can you please give us some hints on how to resolve this and complete the installation? Thank you in advance.

Regards,
Alex
![glami_pixel_screenshot](https://user-images.githubusercontent.com/83797643/221222031-790e182b-ed3e-4d9d-a092-a5f08ffaabe2.png)

**Comment by Bashev** [comment]
@jolovies can you try with:

`composer require webcodebg/module-glami`

I forgot to update installation instructions.

Feel free to contact me, i can support installation and configuration process.

**Comment by Bashev** [comment]
fixed in version 104.1.1
